# 使用dplyr进行数据转换

1. 使用dplyr进行数据转换主要使用***tidyverse***包和***nycflights13***数据包

2. dplyr五个核心函数

    a. 按值筛选函数***filter()***
    
    b. 对行重新排序函数***arrange()***
    
    c. 按名称选取变量函数***select()***
    
    d. 创建新变量函数***mutate()***
    
    e. 获得摘要统计量函数***summarize()***

In [1]:
# 加载包
library(tidyverse)
library(nycflights13)

─ Attaching packages ──────────────────── tidyverse 1.2.1 ─
✔ ggplot2 3.1.0     ✔ purrr   0.2.5
✔ tibble  1.4.2     ✔ dplyr   0.7.8
✔ tidyr   0.8.2     ✔ stringr 1.3.1
✔ readr   1.1.1     ✔ forcats 0.3.0
─ Conflicts ───────────────────── tidyverse_conflicts() ─
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


查看flights数据
![tibble截图](image/tibble.png)
jupyter对于tibble数据框的显示不如rstudio好，看截图

In [2]:
head(flights)
str(flights)

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	336776 obs. of  19 variables:
 $ year          : int  2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
 $ month         : int  1 1 1 1 1 1 1 1 1 1 ...
 $ day           : int  1 1 1 1 1 1 1 1 1 1 ...
 $ dep_time      : int  517 533 542 544 554 554 555 557 557 558 ...
 $ sched_dep_time: int  515 529 540 545 600 558 600 600 600 600 ...
 $ dep_delay     : num  2 4 2 -1 -6 -4 -5 -3 -3 -2 ...
 $ arr_time      : int  830 850 923 1004 812 740 913 709 838 753 ...
 $ sched_arr_time: int  819 830 850 1022 837 728 854 723 846 745 ...
 $ arr_delay     : num  11 20 33 -18 -25 12 19 -14 -8 8 ...
 $ carrier       : chr  "UA" "UA" "AA" "B6" ...
 $ flight        : int  1545 1714 1141 725 461 1696 507 5708 79 301 ...
 $ tailnum       : chr  "N14228" "N24211" "N619AA" "N804JB" ...
 $ origin        : chr  "EWR" "LGA" "JFK" "JFK" ...
 $ dest          : chr  "IAH" "IAH" "MIA" "BQN" ...
 $ air_time      : num  227 227 160 183 116 150 158 53 140 138 ...
 $ distanc

## 使用filter()筛选行

In [3]:
# 筛选1月1日的航班,数据有点多，使用head()函数仅仅显示前6行,下同
head(filter(flights, month == 1, day == 1))
#注意是两个等号“==”

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

dplyr函数不会修改输入，如果要保存结果需要使用赋值操作“<-”

如果既要输出结果，又要保存结果，则使用"()"将赋值操作括起来

In [4]:
head(fm1d1 <- filter(flights, month == 1, day == 1))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

除了使用等于"=="，还可以使用其他比较运算符"!="、">"、"<="，以及逻辑运算符
"&"、"|"、"!"

In [5]:
# 实践一下，找出8月中旬的航班与12月的航班
head(eord <- filter(flights, month == 8 & day >= 10 & day <= 20 | month == 2))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 2     1   456      500            -4         652      648          
2 2013 2     1   520      525            -5         816      820          
3 2013 2     1   527      530            -3         837      829          
4 2013 2     1   532      540            -8        1007     1017          
5 2013 2     1   540      540             0         859      850          
6 2013 2     1   552      600            -8         714      715          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1   4       US      1117   N197UW  EWR    CLT   98       529     5     0    
2  -4       UA      1018   N24211  EWR    IAH  209      1400     5    25    
3   8       UA       650   N470UA  LGA    IAH  233      1416     5    30    
4 -10       B6       725   N554JB  JFK    BQN  195      1576     5    40    
5   9       AA      1141   N615AA  JFK    MIA  169      1089     5    40    
6  -1       EV      5716   N829AS  JFK    IAD   58       228     6     0    
  time_hour          
1 2013-02-01 05:00:00
2 2013-02-01 05:00:00
3 2013-02-01 05:00:00
4 2013-02-01 05:00:00
5 2013-02-01 05:00:00
6 2013-02-01 06:00:00

In [6]:
# 检查一下上面筛选的有没有问题
# 使用t()函数转置一下

unique(eord$month)#是否只有8月和12月

t(unique(filter(eord, month == 8)$day))# 8月是否是中旬

matrix(unique(filter(eord, month == 2)$day),ncol = 7, byrow = T)# 12月是否是全月
# 为了显示，转成了矩阵，,刚好2月是7的整数倍，不然不足的就自动填充了

[1] 2 8

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
[1,] 10   11   12   13   14   15   16   17   18   19    20

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]  1    2    3    4    5    6    7  
[2,]  8    9   10   11   12   13   14  
[3,] 15   16   17   18   19   20   21  
[4,] 22   23   24   25   26   27   28

复杂的表达式最好用小括号括起来，看起来更清楚，而且很多复杂表达式可以简化

还有一种操作是"%in%"

In [7]:
# 筛选出7-9月的航班
head(filter(flights, month %in% c(7:9)))
tail(filter(flights, month %in% c(7:9)))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 7     1    1       2029           212       236      2359          
2 2013 7     1    2       2359             3       344       344          
3 2013 7     1   29       2245           104       151         1          
4 2013 7     1   43       2130           193       322        14          
5 2013 7     1   44       2150           174       300       100          
6 2013 7     1   46       2051           235       304      2358          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 157       B6       915   N653JB  JFK    SFO  315      2586     20   29    
2   0       B6      1503   N805JB  JFK    SJU  200      1598     23   59    
3 110       B6       234   N348JB  JFK    BTV   66       266     22   45    
4 188       B6      1371   N794JB  LGA    FLL  143      1076     21   30    
5 120       AA       185   N324AA  JFK    LAX  297      2475     21   50    
6 186       B6       165   N640JB  JFK    PDX  304      2454     20   51    
  time_hour          
1 2013-07-01 20:00:00
2 2013-07-01 23:00:00
3 2013-07-01 22:00:00
4 2013-07-01 21:00:00
5 2013-07-01 21:00:00
6 2013-07-01 20:00:00

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 9     30  NA       1842           NA        NA       2019          
2 2013 9     30  NA       1455           NA        NA       1634          
3 2013 9     30  NA       2200           NA        NA       2312          
4 2013 9     30  NA       1210           NA        NA       1330          
5 2013 9     30  NA       1159           NA        NA       1344          
6 2013 9     30  NA        840           NA        NA       1020          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 NA        EV      5274   N740EV  LGA    BNA  NA       764      18   42    
2 NA        9E      3393   NA      JFK    DCA  NA       213      14   55    
3 NA        9E      3525   NA      LGA    SYR  NA       198      22    0    
4 NA        MQ      3461   N535MQ  LGA    BNA  NA       764      12   10    
5 NA        MQ      3572   N511MQ  LGA    CLE  NA       419      11   59    
6 NA        MQ      3531   N839MQ  LGA    RDU  NA       431       8   40    
  time_hour          
1 2013-09-30 18:00:00
2 2013-09-30 14:00:00
3 2013-09-30 22:00:00
4 2013-09-30 12:00:00
5 2013-09-30 11:00:00
6 2013-09-30 08:00:00

缺失值"NA"是一个复杂的问题，***filter()***函数会自动排除缺失值的行，
***is.na()***可以判别是否是缺失值

书上说可以用***between()***函数简化一些代码，不知如何实现

## 使用arrange()排列行

In [8]:
arrange(flights, desc(month), desc(is.na(dep_time)))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 12    1   NA       1200           NA        NA       1314          
2      2013 12    1   NA        830           NA        NA       1039          
3      2013 12    1   NA       2229           NA        NA       2343          
4      2013 12    1   NA        631           NA        NA        742          
5      2013 12    1   NA        620           NA        NA        826          
6      2013 12    1   NA        700           NA        NA        834          
7      2013 12    2   NA       1050           NA        NA       1259          
8      2013 12    2   NA       1010           NA        NA       1129          
9      2013 12    2   NA       1845           NA        NA       2026          
10     2013 12    3   NA       1640           NA        NA       1838          
11     2013 12    3   NA        915           NA        NA       1056          
12     2013 12    3   NA       1845           NA        NA       2040          
13     2013 12    4   NA       1025           NA        NA       1127          
14     2013 12    4   NA       1259           NA        NA       1454          
15     2013 12    4   NA       1020           NA        NA       1205          
16     2013 12    4   NA       1155           NA        NA       1355          
17     2013 12    4   NA       1845           NA        NA       2040          
18     2013 12    4   NA       1359           NA        NA       1530          
19     2013 12    4   NA        700           NA        NA        835          
20     2013 12    4   NA        850           NA        NA       1132          
21     2013 12    5   NA        925           NA        NA       1106          
22     2013 12    5   NA        825           NA        NA        953          
23     2013 12    5   NA       1815           NA        NA       2127          
24     2013 12    5   NA       1900           NA        NA       2047          
25     2013 12    5   NA       1630           NA        NA       1816          
26     2013 12    5   NA       1700           NA        NA       1913          
27     2013 12    5   NA       1235           NA        NA       1351          
28     2013 12    5   NA       1015           NA        NA       1337          
29     2013 12    5   NA       1130           NA        NA       1333          
30     2013 12    5   NA       1930           NA        NA       2155          
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮             
336747 2013 1     31  2153     2005           108         20     2230          
336748 2013 1     31  2158     1904           174       2355     2109          
336749 2013 1     31  2159     2005           114       2310     2133          
336750 2013 1     31  2201     2045            76       2323     2225          
336751 2013 1     31  2202     2125            37       2320     2240          
336752 2013 1     31  2206     2125            41       2253     2224          
336753 2013 1     31  2206     2030            96       2338     2206          
336754 2013 1     31  2213     2140            33       2345     2306          
336755 2013 1     31  2214     2125            49       2349     2250          
336756 2013 1     31  2215     2000           135       2346     2125          
336757 2013 1     31  2219     1930           169          2     2115          
336758 2013 1     31  2222     1945           157       2343     2105          
336759 2013 1     31  2225     2015           130         14     2210          
336760 2013 1     31  2229     2100            89         26     2250          
336761 2013 1     31  2232     2000           152        110     2232          
336762 2013 1     31  2233     2000           153         41     2224          
336763 2013 1     31  2239     2110            89        123     2355          
336764 2013 1     31  2240     2042           118         29     2231          
336765 

arrange()就三个可说的用法

分别是，正序排、逆序排、NA排前面以及复合排序

In [9]:
# 正序排
head(arrange(flights, month))

head(arrange(flights, dep_time))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013  1    13  1        2249            72       108      2357          
2 2013  1    31  1        2100           181       124      2225          
3 2013 11    13  1        2359             2       442       440          
4 2013 12    16  1        2359             2       447       437          
5 2013 12    20  1        2359             2       430       440          
6 2013 12    26  1        2359             2       437       440          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  71       B6        22   N206JB  JFK    SYR   41       209     22   49    
2 179       WN       530   N550WN  LGA    MDW  127       725     21    0    
3   2       B6      1503   N627JB  JFK    SJU  194      1598     23   59    
4  10       B6       839   N607JB  JFK    BQN  202      1576     23   59    
5 -10       B6      1503   N608JB  JFK    SJU  182      1598     23   59    
6  -3       B6      1503   N527JB  JFK    SJU  197      1598     23   59    
  time_hour          
1 2013-01-13 22:00:00
2 2013-01-31 21:00:00
3 2013-11-13 23:00:00
4 2013-12-16 23:00:00
5 2013-12-20 23:00:00
6 2013-12-26 23:00:00

In [10]:
# 逆序排
head(arrange(flights, desc(day)))

head(arrange(flights, desc(dep_delay)))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     31   1       2100           181       124      2225          
2 2013 1     31   4       2359             5       455       444          
3 2013 1     31   7       2359             8       453       437          
4 2013 1     31  12       2250            82       132         7          
5 2013 1     31  26       2154           152       328        50          
6 2013 1     31  34       2159           155       135      2315          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 179       WN       530   N550WN  LGA    MDW  127       725     21    0    
2  11       B6       739   N599JB  JFK    PSE  206      1617     23   59    
3  16       B6       727   N505JB  JFK    BQN  197      1576     23   59    
4  85       B6        30   N178JB  JFK    ROC   60       264     22   50    
5 158       B6       515   N663JB  EWR    FLL  161      1065     21   54    
6 140       EV      4162   N24128  EWR    BTV   43       266     21   59    
  time_hour          
1 2013-01-31 21:00:00
2 2013-01-31 23:00:00
3 2013-01-31 23:00:00
4 2013-01-31 22:00:00
5 2013-01-31 21:00:00
6 2013-01-31 21:00:00

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1      9   641      900           1301      1242     1530          
2 2013 6     15  1432     1935           1137      1607     2120          
3 2013 1     10  1121     1635           1126      1239     1810          
4 2013 9     20  1139     1845           1014      1457     2210          
5 2013 7     22   845     1600           1005      1044     1815          
6 2013 4     10  1100     1900            960      1342     2211          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 1272      HA        51   N384HA  JFK    HNL  640      4983      9    0    
2 1127      MQ      3535   N504MQ  JFK    CMH   74       483     19   35    
3 1109      MQ      3695   N517MQ  EWR    ORD  111       719     16   35    
4 1007      AA       177   N338AA  JFK    SFO  354      2586     18   45    
5  989      MQ      3075   N665MQ  JFK    CVG   96       589     16    0    
6  931      DL      2391   N959DL  JFK    TPA  139      1005     19    0    
  time_hour          
1 2013-01-09 09:00:00
2 2013-06-15 19:00:00
3 2013-01-10 16:00:00
4 2013-09-20 18:00:00
5 2013-07-22 16:00:00
6 2013-04-10 19:00:00

In [11]:
# NA排前面（默认NA是排在末尾的）
tail(arrange(flights, dep_time))
tail(arrange(flights, desc(dep_time)))

# 使用is.na()函数将NA排在前面
head(arrange(flights, is.na(dep_time)))
## 并没有
head(arrange(flights, desc(is.na(dep_time))))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 9     30  NA       1842           NA        NA       2019          
2 2013 9     30  NA       1455           NA        NA       1634          
3 2013 9     30  NA       2200           NA        NA       2312          
4 2013 9     30  NA       1210           NA        NA       1330          
5 2013 9     30  NA       1159           NA        NA       1344          
6 2013 9     30  NA        840           NA        NA       1020          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 NA        EV      5274   N740EV  LGA    BNA  NA       764      18   42    
2 NA        9E      3393   NA      JFK    DCA  NA       213      14   55    
3 NA        9E      3525   NA      LGA    SYR  NA       198      22    0    
4 NA        MQ      3461   N535MQ  LGA    BNA  NA       764      12   10    
5 NA        MQ      3572   N511MQ  LGA    CLE  NA       419      11   59    
6 NA        MQ      3531   N839MQ  LGA    RDU  NA       431       8   40    
  time_hour          
1 2013-09-30 18:00:00
2 2013-09-30 14:00:00
3 2013-09-30 22:00:00
4 2013-09-30 12:00:00
5 2013-09-30 11:00:00
6 2013-09-30 08:00:00

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 9     30  NA       1842           NA        NA       2019          
2 2013 9     30  NA       1455           NA        NA       1634          
3 2013 9     30  NA       2200           NA        NA       2312          
4 2013 9     30  NA       1210           NA        NA       1330          
5 2013 9     30  NA       1159           NA        NA       1344          
6 2013 9     30  NA        840           NA        NA       1020          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 NA        EV      5274   N740EV  LGA    BNA  NA       764      18   42    
2 NA        9E      3393   NA      JFK    DCA  NA       213      14   55    
3 NA        9E      3525   NA      LGA    SYR  NA       198      22    0    
4 NA        MQ      3461   N535MQ  LGA    BNA  NA       764      12   10    
5 NA        MQ      3572   N511MQ  LGA    CLE  NA       419      11   59    
6 NA        MQ      3531   N839MQ  LGA    RDU  NA       431       8   40    
  time_hour          
1 2013-09-30 18:00:00
2 2013-09-30 14:00:00
3 2013-09-30 22:00:00
4 2013-09-30 12:00:00
5 2013-09-30 11:00:00
6 2013-09-30 08:00:00

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   NA       1630           NA        NA       1815          
2 2013 1     1   NA       1935           NA        NA       2240          
3 2013 1     1   NA       1500           NA        NA       1825          
4 2013 1     1   NA        600           NA        NA        901          
5 2013 1     2   NA       1540           NA        NA       1747          
6 2013 1     2   NA       1620           NA        NA       1746          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 NA        EV      4308   N18120  EWR    RDU  NA        416     16   30    
2 NA        AA       791   N3EHAA  LGA    DFW  NA       1389     19   35    
3 NA        AA      1925   N3EVAA  LGA    MIA  NA       1096     15    0    
4 NA        B6       125   N618JB  JFK    FLL  NA       1069      6    0    
5 NA        EV      4352   N10575  EWR    CVG  NA        569     15   40    
6 NA        EV      4406   N13949  EWR    PIT  NA        319     16   20    
  time_hour          
1 2013-01-01 16:00:00
2 2013-01-01 19:00:00
3 2013-01-01 15:00:00
4 2013-01-01 06:00:00
5 2013-01-02 15:00:00
6 2013-01-02 16:00:00

In [12]:
# 复合排序就是指定多条件进行排序

# 按month正序排、按day逆序排、将dep_delay的NA排在前面
head(arrange(flights, month, desc(day), desc(is.na(dep_delay))))

tail(arrange(flights, month, desc(day), desc(is.na(dep_delay))))

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     31  NA       1145           NA        NA       1410          
2 2013 1     31  NA        817           NA        NA       1127          
3 2013 1     31  NA        800           NA        NA       1122          
4 2013 1     31  NA       1230           NA        NA       1459          
5 2013 1     31  NA       1527           NA        NA       1700          
6 2013 1     31  NA       1545           NA        NA       1815          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1 NA        DL       401   N309DE  EWR    ATL  NA        746     11   45    
2 NA        DL      1109   N330NW  LGA    TPA  NA       1010      8   17    
3 NA        DL      1271   N935DL  JFK    FLL  NA       1069      8    0    
4 NA        EV      3826   N11176  EWR    ATL  NA        746     12   30    
5 NA        EV      3835   N16561  EWR    BNA  NA        748     15   27    
6 NA        DL      1942   N342NB  EWR    ATL  NA        746     15   45    
  time_hour          
1 2013-01-31 11:00:00
2 2013-01-31 08:00:00
3 2013-01-31 08:00:00
4 2013-01-31 12:00:00
5 2013-01-31 15:00:00
6 2013-01-31 15:00:00

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 12    1   2251     2200            51         50       33          
2 2013 12    1   2255     2250             5          1     2356          
3 2013 12    1   2258     2300            -2       2350       10          
4 2013 12    1   2301     1955           186         19     2146          
5 2013 12    1   2321     2300            21         23       28          
6 2013 12    1   2354     2359            -5        429      440          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  17       UA       668   N460UA  LGA    DEN  223      1620     22    0    
2   5       B6      1816   N258JB  JFK    SYR   43       209     22   50    
3 -20       UA      1525   N34282  EWR    BOS   40       200     23    0    
4 153       EV      5038   N615QX  LGA    BHM  122       866     19   55    
5  -5       UA      1446   N12221  EWR    ORD  105       719     23    0    
6 -11       B6      1503   N509JB  JFK    SJU  194      1598     23   59    
  time_hour          
1 2013-12-01 22:00:00
2 2013-12-01 22:00:00
3 2013-12-01 23:00:00
4 2013-12-01 19:00:00
5 2013-12-01 23:00:00
6 2013-12-01 23:00:00

## 使用select()选择列

In [13]:
# select()可以按变量名快速选择子集
head(select(flights, year,month,day))
head(select(flights, year:day))
head(select(flights, -(year:day)))

year month day
1 2013 1     1  
2 2013 1     1  
3 2013 1     1  
4 2013 1     1  
5 2013 1     1  
6 2013 1     1

year month day
1 2013 1     1  
2 2013 1     1  
3 2013 1     1  
4 2013 1     1  
5 2013 1     1  
6 2013 1     1

dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay carrier
1 517      515             2         830      819            11       UA     
2 533      529             4         850      830            20       UA     
3 542      540             2         923      850            33       AA     
4 544      545            -1        1004     1022           -18       B6     
5 554      600            -6         812      837           -25       DL     
6 554      558            -4         740      728            12       UA     
  flight tailnum origin dest air_time distance hour minute time_hour          
1 1545   N14228  EWR    IAH  227      1400     5    15     2013-01-01 05:00:00
2 1714   N24211  LGA    IAH  227      1416     5    29     2013-01-01 05:00:00
3 1141   N619AA  JFK    MIA  160      1089     5    40     2013-01-01 05:00:00
4  725   N804JB  JFK    BQN  183      1576     5    45     2013-01-01 05:00:00
5  461   N668DN  LGA    ATL  116       762     6     0     2013-01-01 06:00:00
6 1696   N39463  EWR    ORD  150       719     5    58     2013-01-01 05:00:00

###  select()函数中的辅助函数

starts_with()、ends_with()、contains()、matches()，分别是什么应该能看出来


In [14]:
head(select(flights, starts_with("dep")))

head(select(flights, ends_with("time")))

head(select(flights, contains("ou")))

head(select(flights, matches("^arr")))# 正则表达式匹配"arr"开头

head(select(flights, matches("[iou]")))# 正则表达式匹配行名包含"iou"的列

# 正则表达式非常有用!!!

dep_time dep_delay
1 517       2       
2 533       4       
3 542       2       
4 544      -1       
5 554      -6       
6 554      -4

dep_time sched_dep_time arr_time sched_arr_time air_time
1 517      515             830      819           227     
2 533      529             850      830           227     
3 542      540             923      850           160     
4 544      545            1004     1022           183     
5 554      600             812      837           116     
6 554      558             740      728           150

hour time_hour          
1 5    2013-01-01 05:00:00
2 5    2013-01-01 05:00:00
3 5    2013-01-01 05:00:00
4 5    2013-01-01 05:00:00
5 6    2013-01-01 06:00:00
6 5    2013-01-01 05:00:00

arr_time arr_delay
1  830      11      
2  850      20      
3  923      33      
4 1004     -18      
5  812     -25      
6  740      12

month dep_time sched_dep_time arr_time sched_arr_time carrier flight tailnum
1 1     517      515             830      819           UA      1545   N14228 
2 1     533      529             850      830           UA      1714   N24211 
3 1     542      540             923      850           AA      1141   N619AA 
4 1     544      545            1004     1022           B6       725   N804JB 
5 1     554      600             812      837           DL       461   N668DN 
6 1     554      558             740      728           UA      1696   N39463 
  origin air_time distance hour minute time_hour          
1 EWR    227      1400     5    15     2013-01-01 05:00:00
2 LGA    227      1416     5    29     2013-01-01 05:00:00
3 JFK    160      1089     5    40     2013-01-01 05:00:00
4 JFK    183      1576     5    45     2013-01-01 05:00:00
5 LGA    116       762     6     0     2013-01-01 06:00:00
6 EWR    150       719     5    58     2013-01-01 05:00:00

In [15]:
# 使用rename()函数重命名将tailnum改为tail_t_num
head(select(flights, contains("num")))

head(select(rename(flights, tail_t_num = tailnum),contains("num")))

tailnum
1 N14228 
2 N24211 
3 N619AA 
4 N804JB 
5 N668DN 
6 N39463

tail_t_num
1 N14228    
2 N24211    
3 N619AA    
4 N804JB    
5 N668DN    
6 N39463

In [16]:
# 使用everything()函数将某列或某几列放到前面
head(select(flights, time_hour, tailnum, everything()))

time_hour           tailnum year month day dep_time sched_dep_time dep_delay
1 2013-01-01 05:00:00 N14228  2013 1     1   517      515             2       
2 2013-01-01 05:00:00 N24211  2013 1     1   533      529             4       
3 2013-01-01 05:00:00 N619AA  2013 1     1   542      540             2       
4 2013-01-01 05:00:00 N804JB  2013 1     1   544      545            -1       
5 2013-01-01 06:00:00 N668DN  2013 1     1   554      600            -6       
6 2013-01-01 05:00:00 N39463  2013 1     1   554      558            -4       
  arr_time sched_arr_time arr_delay carrier flight origin dest air_time
1  830      819            11       UA      1545   EWR    IAH  227     
2  850      830            20       UA      1714   LGA    IAH  227     
3  923      850            33       AA      1141   JFK    MIA  160     
4 1004     1022           -18       B6       725   JFK    BQN  183     
5  812      837           -25       DL       461   LGA    ATL  116     
6  740      728            12       UA      1696   EWR    ORD  150     
  distance hour minute
1 1400     5    15    
2 1416     5    29    
3 1089     5    40    
4 1576     5    45    
5  762     6     0    
6  719     5    58

In [17]:
#  one_of()函数的作用是什么？

vars <-c( "year", "month", "day", "dep_delay", "arr_delay")

head(select(flights, vars))

year month day dep_delay arr_delay
1 2013 1     1    2         11      
2 2013 1     1    4         20      
3 2013 1     1    2         33      
4 2013 1     1   -1        -18      
5 2013 1     1   -6        -25      
6 2013 1     1   -4         12

## 使用mutate()添加新变量

In [18]:
# mutate就是以原有列为基础进行运算，在最后添加新的列

flights_sml <- select(flights, year:day,ends_with("delay"),
                     distance, air_time)

head(mutate(flights_sml, gain = arr_delay - dep_delay,
      speed = distance / air_time * 60))

year month day dep_delay arr_delay distance air_time gain speed   
1 2013 1     1    2         11       1400     227        9  370.0441
2 2013 1     1    4         20       1416     227       16  374.2731
3 2013 1     1    2         33       1089     160       31  408.3750
4 2013 1     1   -1        -18       1576     183      -17  516.7213
5 2013 1     1   -6        -25        762     116      -19  394.1379
6 2013 1     1   -4         12        719     150       16  287.6000

In [19]:
head(flights_sml)# 原始数据依旧没有修改

year month day dep_delay arr_delay distance air_time
1 2013 1     1    2         11       1400     227     
2 2013 1     1    4         20       1416     227     
3 2013 1     1    2         33       1089     160     
4 2013 1     1   -1        -18       1576     183     
5 2013 1     1   -6        -25        762     116     
6 2013 1     1   -4         12        719     150

In [20]:
head(mutate(flights_sml,
      gain = arr_delay - dep_delay,
      hours = air_time / 60,
      gain_per_hour = gain / hours))

year month day dep_delay arr_delay distance air_time gain hours   
1 2013 1     1    2         11       1400     227        9  3.783333
2 2013 1     1    4         20       1416     227       16  3.783333
3 2013 1     1    2         33       1089     160       31  2.666667
4 2013 1     1   -1        -18       1576     183      -17  3.050000
5 2013 1     1   -6        -25        762     116      -19  1.933333
6 2013 1     1   -4         12        719     150       16  2.500000
  gain_per_hour
1  2.378855    
2  4.229075    
3 11.625000    
4 -5.573770    
5 -9.827586    
6  6.400000

In [21]:
# 如果只想保留新变量，使用transmute()函数
head(transmute(flights_sml,
      gain = arr_delay - dep_delay,
      hours = air_time / 60,
      gain_per_hour = gain / hours))

head(flights_sml)# 原数据依旧没变

gain hours    gain_per_hour
1   9  3.783333  2.378855    
2  16  3.783333  4.229075    
3  31  2.666667 11.625000    
4 -17  3.050000 -5.573770    
5 -19  1.933333 -9.827586    
6  16  2.500000  6.400000

year month day dep_delay arr_delay distance air_time
1 2013 1     1    2         11       1400     227     
2 2013 1     1    4         20       1416     227     
3 2013 1     1    2         33       1089     160     
4 2013 1     1   -1        -18       1576     183     
5 2013 1     1   -6        -25        762     116     
6 2013 1     1   -4         12        719     150

### 常用创建函数

创建新变量的多种函数可供你同mutate()一同使用。
最重要的一点是，这种函数必须是向量化的：
它必须接受一个向量作为输入，并返回一个向量作为输出，
而且输入向量与输出向量具有同样数目的分量。

1. 算数运算符：+ 、- 、* 、/ 、^

2. 模运算符：%/%(整除) 、%%(取余)

3. 对数：log() 、logx() 、log10()

4. 偏移函数：lead() 、lag()

5. 逻辑比较：< 、<= 、> 、>= 、!=

6. 排秩

7. 累加和滚动聚合

In [23]:
# 偏移函数一看例子就懂，不解释
t(x <- 1:10)
t(lag(x))
t(lead(x))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    2    3    4    5    6    7    8    9    10

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] NA   1    2    3    4    5    6    7    8    9

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 2    3    4    5    6    7    8    9    10   NA

这样看不出来偏移函数用法，学了group_by()
之后还不明白可以参考下面的链接
[巧用偏移函数](https://cloud.tencent.com/developer/article/1429995)

秩(rank)，顾名思义就是秩序的意思，不懂的百度

几个排秩函数：min_rank()、row_number()、dense_rank()、
percent_rank()、cume_dist()、mtile()

目前会用min_rank()即可

In [33]:
y <- c(1,2,3,2,NA,4)
t(sort(y))
t(min_rank(y))# 最小值获得最前面的名次
t(min_rank(desc(y)))

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    2    3    4

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    4    2    NA   5

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 5    3    2    3    NA   1

In [37]:
## 累加和滚动聚合也不难

# R提供了计算累加和、累加积、累加最小值和累加最大值的函数：

# cumsum()、cumprod()、cummin()和cummax()；

# dplyr还提供了cummean()函数以计算累加均值。

t(x <- 1:10)
 
t(cumsum(x))# 和

t(cumprod(x)) # 积

t(cummin(x))# min

t(cummax(x))# max

t(cummean(x))# mean

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    2    3    4    5    6    7    8    9    10

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    3    6    10   15   21   28   36   45   55

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]  [,9]   [,10]  
[1,] 1    2    6    24   120  720  5040 40320 362880 3628800

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    2    3    4    5    6    7    8    9    10

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1.5  2    2.5  3    3.5  4    4.5  5    5.5

cummin()和cummax()不是很好理解吧

和下面的例子对比也许就懂了

In [43]:
t(z <- 10:1)
t(cummin(z))
t(cummax(z))

# 还可以执行example(cummin)看一下官方例子

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 10   9    8    7    6    5    4    3    2    1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 10   9    8    7    6    5    4    3    2    1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 10   10   10   10   10   10   10   10   10   10

In [39]:
example(cummin)


cummin> cumsum(1:10)
 [1]  1  3  6 10 15 21 28 36 45 55

cummin> cumprod(1:10)
 [1]       1       2       6      24     120     720    5040   40320  362880
[10] 3628800

cummin> cummin(c(3:1, 2:0, 4:2))
[1] 3 2 1 1 1 0 0 0 0

cummin> cummax(c(3:1, 2:0, 4:2))
[1] 3 3 3 3 3 3 4 4 4


## 使用summarize()进行分组摘要

In [47]:
summarise(flights, delay = mean(dep_delay, na.rm = T))

delay   
1 12.63907

In [49]:
head(flights)

year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819          
2 2013 1     1   533      529             4         850      830          
3 2013 1     1   542      540             2         923      850          
4 2013 1     1   544      545            -1        1004     1022          
5 2013 1     1   554      600            -6         812      837          
6 2013 1     1   554      558            -4         740      728          
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15    
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29    
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40    
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45    
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0    
6  12       UA      1696   N39463  EWR    ORD  150       719     5    58    
  time_hour          
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00

In [53]:
range(1,3,5,10)

[1]  1 10